import Head from "next/head";
import React from "react";

import styles from "./Home.module.css";

import Header from "../widgets/Header/Header";
import { playfairDisplay } from "../constants/fonts";
import GhostButton from "../components/Button/GhostButton";
import { useRouter } from "next/router";

type Props = {};

const ErrorPage = (props: Props) => {
  const router = useRouter();

  function navigateHome() {
    router.push("/");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Page not found | SYNONYM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>
      <main className={styles.mainSection}>
        <div className={styles.orWrapper}>
          <div className={styles.line}></div>
          <div className={styles.or}>404</div>
          <div className={styles.line}></div>
        </div>
        <div className={styles.title + " " + playfairDisplay.className}>
          The page was not found
        </div>

        <GhostButton
          onClick={() => navigateHome()}
          text="HOME"
          reactive={true}
        ></GhostButton>
      </main>
    </div>
  );
};

export default ErrorPage;
