import Head from "next/head";
import React, { useState } from "react";
import { useRouter } from "next/router";

import styles from "./Home.module.css";

import { roboto, playfairDisplay } from "../constants/fonts";

import Header from "../widgets/Header/Header";
import GhostButton from "../components/Button/GhostButton";
import SearchBar from "../components/SearchBar/SearchBar";
import AddWord from "../widgets/AddWord/AddWord";

export default function Home() {
  const [input, setInput] = useState("");
  const [showAddWord, setShowAddWord] = useState(false);
  const router = useRouter();

  function handleInput(event: React.ChangeEvent<HTMLInputElement>) {
    setInput(event.target.value);
  }

  function handleSearch(event: React.FormEvent) {
    event.preventDefault();
    if (input != "") {
      router.push(`/lookup/${input}`);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Look up synonyms for words | SYNONYM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>
      <main className={styles.mainSection}>
        <div className={styles.title + " " + playfairDisplay.className}>
          Enter a word to look up
        </div>
        <div className={styles.inputWrapper}>
          <form onSubmit={handleSearch}>
            <SearchBar
              reactive={true}
              value={input}
              onChange={handleInput}
              placeholder="Type here"
            ></SearchBar>
          </form>
        </div>
        <div className={styles.orWrapper}>
          <div className={styles.line}></div>
          <div className={styles.or + " " + roboto.className}>or</div>
          <div className={styles.line}></div>
        </div>

        <GhostButton
          onClick={() => setShowAddWord(true)}
          text="ADD WORD"
          reactive={true}
        ></GhostButton>
      </main>

      {showAddWord ? (
        <AddWord closeOverlay={() => setShowAddWord(false)}></AddWord>
      ) : (
        ""
      )}
    </div>
  );
}
